version: "3"

networks:
  consul-net:

services:
  consul1:
    image: consul:1.14
    container_name: consul_node1
    command: agent -server -bootstrap-expect=3 -node=consul_node1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    volumes:
      - ./data/1:/consul/data
    networks:
      - consul-net

  consul2:
      image: consul:1.14
      container_name: consul_node2
      command: agent -server -retry-join=consul_node1 -node=consul_node2 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
      volumes:
        - ./data/2:/consul/data
      depends_on:
        - consul1
      networks:
        - consul-net

  consul3:
      image: consul:1.14
      container_name: consul_node3
      command: agent -server -retry-join=consul_node1 -node=consul_node3 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
      volumes:
        - ./data/3:/consul/data
      depends_on:
        - consul1
      networks:
        - consul-net

  consul4:
      image: consul:1.14
      container_name: consul_node4
      command: agent -retry-join=consul_node1 -node=consul_node4 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
      volumes:
        - ./data/4:/consul/data
      ports:
        - 8500:8500
      depends_on:
        - consul2
        - consul3
      networks:
        - consul-net