version: "3"

networks:
  work_work:
    external: true

services:
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.18
    container_name: jaeger-collector
    restart: always
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - LOG_LEVEL=debug
    networks:
      - work_net
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "14250:14250"
      - "9411:9411"

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.18
    container_name: jaeger-agent
    restart: always
    environment:
      - REPORTER_GRPC_HOST_PORT=jaeger-collector:14250
      - LOG_LEVEL=debug
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
    networks:
      - work_work
    depends_on:
      - jaeger-collector

  jaeger-query:
    image: jaegertracing/jaeger-query:1.18
    restart: always
    container_name: jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=elasticsearch:9200
      - LOG_LEVEL=debug
    ports:
      - 16686:16686
    networks:
      - work_net