version: "3"

networks:
  work_net:
    external: true

services:
  kafka-map:
    container_name: kafka-map
    image: dushixiang/kafka-map:latest
    ports:
      - 8055:8080
    volumes:
      - ./kafka-map/data:/usr/local/kafka-map/data
    environment:
      - "DEFAULT_USERNAME=admin"
      - "DEFAULT_PASSWORD=admin"
    restart: always
    networks:
      - work_net

  hystrix-dashboard:
    container_name: hystrix-dashboard
    image: cap1573/hystrix-dashboard
    restart: always
    ports:
      - 9002:9002
    networks:
      - work_net