version: '3'

services:
  redis:
    image: redis:6.2
    container_name: redis-6.2
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - ./redis/config:/usr/local/etc/redis
      - ./redis/data:/data
    networks:
      - net
  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    networks:
      - net
  nginx:
    image: nginx:stable-alpine-perl
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net


networks:
  net:
    driver: bridge