http.host: 0.0.0.0
log.level: debug
xpack.monitoring.elasticsearch.hosts:
- http://elasticsearch:9200
xpack.monitoring.elasticsearch.password: "7284665"
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.enabled: true
